(generic_command
  command: (command_name) @conceal
  (#any-of? @conceal "\\emph" "\\mathit" "\\textit" "\\mathbf" "\\textbf")
  (#set! conceal ""))

((generic_command
   command: (command_name)
   arg: (curly_group)) @conceal
 (#any-of? @conceal 
  "\\mathbb{A}" "\\mathbb{B}" "\\mathbb{C}" "\\mathbb{D}" "\\mathbb{E}" 
  "\\mathbb{F}" "\\mathbb{G}" "\\mathbb{H}" "\\mathbb{I}" "\\mathbb{J}" 
  "\\mathbb{K}" "\\mathbb{L}" "\\mathbb{M}" "\\mathbb{N}" "\\mathbb{O}" 
  "\\mathbb{P}" "\\mathbb{Q}" "\\mathbb{R}" "\\mathbb{S}" "\\mathbb{T}" 
  "\\mathbb{U}" "\\mathbb{V}" "\\mathbb{W}" "\\mathbb{X}" "\\mathbb{Y}" 
  "\\mathbb{Z}" "\\mathsf{a}" "\\mathsf{b}" "\\mathsf{c}" "\\mathsf{d}" 
  "\\mathsf{e}" "\\mathsf{f}" "\\mathsf{g}" "\\mathsf{h}" "\\mathsf{i}" 
  "\\mathsf{j}" "\\mathsf{k}" "\\mathsf{l}" "\\mathsf{m}" "\\mathsf{n}" 
  "\\mathsf{o}" "\\mathsf{p}" "\\mathsf{q}" "\\mathsf{r}" "\\mathsf{s}" 
  "\\mathsf{t}" "\\mathsf{u}" "\\mathsf{v}" "\\mathsf{w}" "\\mathsf{x}" 
  "\\mathsf{y}" "\\mathsf{z}" "\\mathsf{A}" "\\mathsf{B}" "\\mathsf{C}" 
  "\\mathsf{D}" "\\mathsf{E}" "\\mathsf{F}" "\\mathsf{G}" "\\mathsf{H}" 
  "\\mathsf{I}" "\\mathsf{J}" "\\mathsf{K}" "\\mathsf{L}" "\\mathsf{M}" 
  "\\mathsf{N}" "\\mathsf{O}" "\\mathsf{P}" "\\mathsf{Q}" "\\mathsf{R}" 
  "\\mathsf{S}" "\\mathsf{T}" "\\mathsf{U}" "\\mathsf{V}" "\\mathsf{W}" 
  "\\mathsf{X}" "\\mathsf{Y}" "\\mathsf{Z}" "\\mathfrak{a}" "\\mathfrak{b}" 
  "\\mathfrak{c}" "\\mathfrak{d}" "\\mathfrak{e}" "\\mathfrak{f}" "\\mathfrak{g}" 
  "\\mathfrak{h}" "\\mathfrak{i}" "\\mathfrak{j}" "\\mathfrak{k}" "\\mathfrak{l}" 
  "\\mathfrak{m}" "\\mathfrak{n}" "\\mathfrak{o}" "\\mathfrak{p}" "\\mathfrak{q}" 
  "\\mathfrak{r}" "\\mathfrak{s}" "\\mathfrak{t}" "\\mathfrak{u}" "\\mathfrak{v}" 
  "\\mathfrak{w}" "\\mathfrak{x}" "\\mathfrak{y}" "\\mathfrak{z}" "\\mathfrak{A}" 
  "\\mathfrak{B}" "\\mathfrak{C}" "\\mathfrak{D}" "\\mathfrak{E}" "\\mathfrak{F}" 
  "\\mathfrak{G}" "\\mathfrak{H}" "\\mathfrak{I}" "\\mathfrak{J}" "\\mathfrak{K}" 
  "\\mathfrak{L}" "\\mathfrak{M}" "\\mathfrak{N}" "\\mathfrak{O}" "\\mathfrak{P}" 
  "\\mathfrak{Q}" "\\mathfrak{R}" "\\mathfrak{S}" "\\mathfrak{T}" "\\mathfrak{U}" 
  "\\mathfrak{V}" "\\mathfrak{W}" "\\mathfrak{X}" "\\mathfrak{Y}" "\\mathfrak{Z}" 
  "\\mathscr{A}" "\\mathscr{B}" "\\mathscr{C}" "\\mathscr{D}" "\\mathscr{E}" 
  "\\mathscr{F}" "\\mathscr{G}" "\\mathscr{H}" "\\mathscr{I}" "\\mathscr{J}" 
  "\\mathscr{K}" "\\mathscr{L}" "\\mathscr{M}" "\\mathscr{N}" "\\mathscr{O}" 
  "\\mathscr{P}" "\\mathscr{Q}" "\\mathscr{R}" "\\mathscr{S}" "\\mathscr{T}" 
  "\\mathscr{U}" "\\mathscr{V}" "\\mathscr{W}" "\\mathscr{X}" "\\mathscr{Y}" 
  "\\mathscr{Z}" "\\mathcal{A}" "\\mathcal{B}" "\\mathcal{C}" "\\mathcal{D}" 
  "\\mathcal{E}" "\\mathcal{F}" "\\mathcal{G}" "\\mathcal{H}" "\\mathcal{I}" 
  "\\mathcal{J}" "\\mathcal{K}" "\\mathcal{L}" "\\mathcal{M}" "\\mathcal{N}" 
  "\\mathcal{O}" "\\mathcal{P}" "\\mathcal{Q}" "\\mathcal{R}" "\\mathcal{S}" 
  "\\mathcal{T}" "\\mathcal{U}" "\\mathcal{V}" "\\mathcal{W}" "\\mathcal{X}" 
  "\\mathcal{Y}" "\\mathcal{Z}" "\\mathrm{A}" "\\mathrm{B}" "\\mathrm{C}"
  "\\mathrm{D}" "\\mathrm{E}" "\\mathrm{F}" "\\mathrm{G}" "\\mathrm{H}"
  "\\mathrm{I}" "\\mathrm{J}" "\\mathrm{K}" "\\mathrm{L}" "\\mathrm{M}"
  "\\mathrm{N}" "\\mathrm{O}" "\\mathrm{P}" "\\mathrm{Q}" "\\mathrm{R}"
  "\\mathrm{S}" "\\mathrm{T}" "\\mathrm{U}" "\\mathrm{V}" "\\mathrm{W}"
  "\\mathrm{X}" "\\mathrm{Y}" "\\mathrm{Z}" "\\mathrm{a}" "\\mathrm{b}"
  "\\mathrm{c}" "\\mathrm{d}" "\\mathrm{e}" "\\mathrm{f}" "\\mathrm{g}"
  "\\mathrm{h}" "\\mathrm{i}" "\\mathrm{j}" "\\mathrm{k}" "\\mathrm{l}"
  "\\mathrm{m}" "\\mathrm{n}" "\\mathrm{o}" "\\mathrm{p}" "\\mathrm{q}"
  "\\mathrm{r}" "\\mathrm{s}" "\\mathrm{t}" "\\mathrm{u}" "\\mathrm{v}"
  "\\mathrm{w}" "\\mathrm{x}" "\\mathrm{y}" "\\mathrm{z}" "\\mathrm{0}"
  "\\mathrm{1}" "\\mathrm{2}" "\\mathrm{3}" "\\mathrm{4}" "\\mathrm{5}"
  "\\mathrm{6}" "\\mathrm{7}" "\\mathrm{8}" "\\mathrm{9}")
 (#set-pairs! @conceal conceal
  "\\mathbb{A}" "𝔸"
  "\\mathbb{B}" "𝔹"
  "\\mathbb{C}" "ℂ"
  "\\mathbb{D}" "𝔻"
  "\\mathbb{E}" "𝔼"
  "\\mathbb{F}" "𝔽"
  "\\mathbb{G}" "𝔾"
  "\\mathbb{H}" "ℍ"
  "\\mathbb{I}" "𝕀"
  "\\mathbb{J}" "𝕁"
  "\\mathbb{K}" "𝕂"
  "\\mathbb{L}" "𝕃"
  "\\mathbb{M}" "𝕄"
  "\\mathbb{N}" "ℕ"
  "\\mathbb{O}" "𝕆"
  "\\mathbb{P}" "ℙ"
  "\\mathbb{Q}" "ℚ"
  "\\mathbb{R}" "ℝ"
  "\\mathbb{S}" "𝕊"
  "\\mathbb{T}" "𝕋"
  "\\mathbb{U}" "𝕌"
  "\\mathbb{V}" "𝕍"
  "\\mathbb{W}" "𝕎"
  "\\mathbb{X}" "𝕏"
  "\\mathbb{Y}" "𝕐"
  "\\mathbb{Z}" "ℤ"
  "\\mathsf{a}" "𝖺"
  "\\mathsf{b}" "𝖻"
  "\\mathsf{c}" "𝖼"
  "\\mathsf{d}" "𝖽"
  "\\mathsf{e}" "𝖾"
  "\\mathsf{f}" "𝖿"
  "\\mathsf{g}" "𝗀"
  "\\mathsf{h}" "𝗁"
  "\\mathsf{i}" "𝗂"
  "\\mathsf{j}" "𝗃"
  "\\mathsf{k}" "𝗄"
  "\\mathsf{l}" "𝗅"
  "\\mathsf{m}" "𝗆"
  "\\mathsf{n}" "𝗇"
  "\\mathsf{o}" "𝗈"
  "\\mathsf{p}" "𝗉"
  "\\mathsf{q}" "𝗊"
  "\\mathsf{r}" "𝗋"
  "\\mathsf{s}" "𝗌"
  "\\mathsf{t}" "𝗍"
  "\\mathsf{u}" "𝗎"
  "\\mathsf{v}" "𝗏"
  "\\mathsf{w}" "𝗐"
  "\\mathsf{x}" "𝗑"
  "\\mathsf{y}" "𝗒"
  "\\mathsf{z}" "𝗓"
  "\\mathsf{A}" "𝖠"
  "\\mathsf{B}" "𝖡"
  "\\mathsf{C}" "𝖢"
  "\\mathsf{D}" "𝖣"
  "\\mathsf{E}" "𝖤"
  "\\mathsf{F}" "𝖥"
  "\\mathsf{G}" "𝖦"
  "\\mathsf{H}" "𝖧"
  "\\mathsf{I}" "𝖨"
  "\\mathsf{J}" "𝖩"
  "\\mathsf{K}" "𝖪"
  "\\mathsf{L}" "𝖫"
  "\\mathsf{M}" "𝖬"
  "\\mathsf{N}" "𝖭"
  "\\mathsf{O}" "𝖮"
  "\\mathsf{P}" "𝖯"
  "\\mathsf{Q}" "𝖰"
  "\\mathsf{R}" "𝖱"
  "\\mathsf{S}" "𝖲"
  "\\mathsf{T}" "𝖳"
  "\\mathsf{U}" "𝖴"
  "\\mathsf{V}" "𝖵"
  "\\mathsf{W}" "𝖶"
  "\\mathsf{X}" "𝖷"
  "\\mathsf{Y}" "𝖸"
  "\\mathsf{Z}" "𝖹"
  "\\mathfrak{a}" "𝔞"
  "\\mathfrak{b}" "𝔟"
  "\\mathfrak{c}" "𝔠"
  "\\mathfrak{d}" "𝔡"
  "\\mathfrak{e}" "𝔢"
  "\\mathfrak{f}" "𝔣"
  "\\mathfrak{g}" "𝔤"
  "\\mathfrak{h}" "𝔥"
  "\\mathfrak{i}" "𝔦"
  "\\mathfrak{j}" "𝔧"
  "\\mathfrak{k}" "𝔨"
  "\\mathfrak{l}" "𝔩"
  "\\mathfrak{m}" "𝔪"
  "\\mathfrak{n}" "𝔫"
  "\\mathfrak{o}" "𝔬"
  "\\mathfrak{p}" "𝔭"
  "\\mathfrak{q}" "𝔮"
  "\\mathfrak{r}" "𝔯"
  "\\mathfrak{s}" "𝔰"
  "\\mathfrak{t}" "𝔱"
  "\\mathfrak{u}" "𝔲"
  "\\mathfrak{v}" "𝔳"
  "\\mathfrak{w}" "𝔴"
  "\\mathfrak{x}" "𝔵"
  "\\mathfrak{y}" "𝔶"
  "\\mathfrak{z}" "𝔷"
  "\\mathfrak{A}" "𝔄"
  "\\mathfrak{B}" "𝔅"
  "\\mathfrak{C}" "ℭ"
  "\\mathfrak{D}" "𝔇"
  "\\mathfrak{E}" "𝔈"
  "\\mathfrak{F}" "𝔉"
  "\\mathfrak{G}" "𝔊"
  "\\mathfrak{H}" "ℌ"
  "\\mathfrak{I}" "ℑ"
  "\\mathfrak{J}" "𝔍"
  "\\mathfrak{K}" "𝔎"
  "\\mathfrak{L}" "𝔏"
  "\\mathfrak{M}" "𝔐"
  "\\mathfrak{N}" "𝔑"
  "\\mathfrak{O}" "𝔒"
  "\\mathfrak{P}" "𝔓"
  "\\mathfrak{Q}" "𝔔"
  "\\mathfrak{R}" "ℜ"
  "\\mathfrak{S}" "𝔖"
  "\\mathfrak{T}" "𝔗"
  "\\mathfrak{U}" "𝔘"
  "\\mathfrak{V}" "𝔙"
  "\\mathfrak{W}" "𝔚"
  "\\mathfrak{X}" "𝔛"
  "\\mathfrak{Y}" "𝔜"
  "\\mathfrak{Z}" "ℨ"
  "\\mathscr{A}" "𝓐"
  "\\mathscr{B}" "𝓑"
  "\\mathscr{C}" "𝓒"
  "\\mathscr{D}" "𝓓"
  "\\mathscr{E}" "𝓔"
  "\\mathscr{F}" "𝓕"
  "\\mathscr{G}" "𝓖"
  "\\mathscr{H}" "𝓗"
  "\\mathscr{I}" "𝓘"
  "\\mathscr{J}" "𝓙"
  "\\mathscr{K}" "𝓚"
  "\\mathscr{L}" "𝓛"
  "\\mathscr{M}" "𝓜"
  "\\mathscr{N}" "𝓝"
  "\\mathscr{O}" "𝓞"
  "\\mathscr{P}" "𝓟"
  "\\mathscr{Q}" "𝓠"
  "\\mathscr{R}" "𝓡"
  "\\mathscr{S}" "𝓢"
  "\\mathscr{T}" "𝓣"
  "\\mathscr{U}" "𝓤"
  "\\mathscr{V}" "𝓥"
  "\\mathscr{W}" "𝓦"
  "\\mathscr{X}" "𝓧"
  "\\mathscr{Y}" "𝓨"
  "\\mathscr{Z}" "𝓩"
  "\\mathcal{A}" "𝓐"
  "\\mathcal{B}" "𝓑"
  "\\mathcal{C}" "𝓒"
  "\\mathcal{D}" "𝓓"
  "\\mathcal{E}" "𝓔"
  "\\mathcal{F}" "𝓕"
  "\\mathcal{G}" "𝓖"
  "\\mathcal{H}" "𝓗"
  "\\mathcal{I}" "𝓘"
  "\\mathcal{J}" "𝓙"
  "\\mathcal{K}" "𝓚"
  "\\mathcal{L}" "𝓛"
  "\\mathcal{M}" "𝓜"
  "\\mathcal{N}" "𝓝"
  "\\mathcal{O}" "𝓞"
  "\\mathcal{P}" "𝓟"
  "\\mathcal{Q}" "𝓠"
  "\\mathcal{R}" "𝓡"
  "\\mathcal{S}" "𝓢"
  "\\mathcal{T}" "𝓣"
  "\\mathcal{U}" "𝓤"
  "\\mathcal{V}" "𝓥"
  "\\mathcal{W}" "𝓦"
  "\\mathcal{X}" "𝓧"
  "\\mathcal{Y}" "𝓨"
  "\\mathcal{Z}" "𝓩"
  "\\mathrm{A}" "𝐀"
  "\\mathrm{B}" "𝐁"
  "\\mathrm{C}" "𝐂"
  "\\mathrm{D}" "𝐃"
  "\\mathrm{E}" "𝐄"
  "\\mathrm{F}" "𝐅"
  "\\mathrm{G}" "𝐆"
  "\\mathrm{H}" "𝐇"
  "\\mathrm{I}" "𝐈"
  "\\mathrm{J}" "𝐉"
  "\\mathrm{K}" "𝐊"
  "\\mathrm{L}" "𝐋"
  "\\mathrm{M}" "𝐌"
  "\\mathrm{N}" "𝐍"
  "\\mathrm{O}" "𝐎"
  "\\mathrm{P}" "𝐏"
  "\\mathrm{Q}" "𝐐"
  "\\mathrm{R}" "𝐑"
  "\\mathrm{S}" "𝐒"
  "\\mathrm{T}" "𝐓"
  "\\mathrm{U}" "𝐔"
  "\\mathrm{V}" "𝐕"
  "\\mathrm{W}" "𝐖"
  "\\mathrm{X}" "𝐗"
  "\\mathrm{Y}" "𝐘"
  "\\mathrm{Z}" "𝐙"
  "\\mathrm{a}" "𝐚"
  "\\mathrm{b}" "𝐛"
  "\\mathrm{c}" "𝐜"
  "\\mathrm{d}" "𝐝"
  "\\mathrm{e}" "𝐞"
  "\\mathrm{f}" "𝐟"
  "\\mathrm{g}" "𝐠"
  "\\mathrm{h}" "𝐡"
  "\\mathrm{i}" "𝐢"
  "\\mathrm{j}" "𝐣"
  "\\mathrm{k}" "𝐤"
  "\\mathrm{l}" "𝐥"
  "\\mathrm{m}" "𝐦"
  "\\mathrm{n}" "𝐧"
  "\\mathrm{o}" "𝐨"
  "\\mathrm{p}" "𝐩"
  "\\mathrm{q}" "𝐪"
  "\\mathrm{r}" "𝐫"
  "\\mathrm{s}" "𝐬"
  "\\mathrm{t}" "𝐭"
  "\\mathrm{u}" "𝐮"
  "\\mathrm{v}" "𝐯"
  "\\mathrm{w}" "𝐰"
  "\\mathrm{x}" "𝐱"
  "\\mathrm{y}" "𝐲"
  "\\mathrm{z}" "𝐳"
  "\\mathrm{0}" "𝟎"
  "\\mathrm{1}" "𝟏"
  "\\mathrm{2}" "𝟐"
  "\\mathrm{3}" "𝟑"
  "\\mathrm{4}" "𝟒"
  "\\mathrm{5}" "𝟓"
  "\\mathrm{6}" "𝟔"
  "\\mathrm{7}" "𝟕"
  "\\mathrm{8}" "𝟖"
  "\\mathrm{9}" "𝟗"))
